config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/bienvenida", to:"home#index"

  root to: "home#index"

  get "articles", to: "articles#index"
  get "articles/new", to: "articles#new", as: :new_articles
  get "articles/:id", to: "articles#show"
  get "articles/:id/edit", to: "articles#edit"
  patch "articles/:id", to: "articles#update", as: :article
  post "articles", to: "articles#create"
  delete "articles/:id", to: "articles#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:show, :edit, :update, :destroy] #o except: [:new, :create]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    #@article = Article.find(params[:id]) como esto lo declare en el before action, show ahora puede quedar como una accion vacia pero TENGO QUE DECLARARLA
    #el id aca es un simbolo, a diferencia de en las rutas que es un comodin
  end

  def edit
    #@article = Article.find(params[:id])
  end

  def update
    #@article = Article.find(params[:id])
    @article.update(title: params[:article][:title], content: params[:article] [:content])
    #los parametros vienen de "article" que es nombre del modelo y de title que es el controlador de las vista.
    redirect_to @article
  end

  def new
    @article = Article.new 
    #crea un articulo nuevo vacio. La variable de instancia permite ser accedida desde la vista que llama a la accion new. Busca una vista "new" y va a permitir que usemos la variable
    @article.title = 'Demo' #esto llena el input con la palabra "demo"
  end

  def create #guarda lo que recibimos del formulario que muestra new
      @article = Article.create(title: params[:article][:title], content: params[:article][:content])
      # crea un nuevo registro en la tabla articulo con el titulo que me viene por parametros desde el control que esta new.html.erb. 
      render json: @article #me muestra un json de lo que me trae de la base de datos en formato json
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! #lo define devise. dice que si hay un usuario deja que se muestre la vista, si no la hay lo que hace es redireccionar a la autenticación
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card padding margin-top">
  <h3 class="text-uppercase"><%= article.id %></h3>
  <p class="text-secondary"><%= article.title %></p>
  <%= link_to "Ver más", article %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %> 
<%# en base al article va a llenar la informacion de dentro del form %>
    <div> 
    <%# #de article tomamos titulo %>
        <%=form.label :title %> 
        <%=form.text_field :title %> 
        <%# y este controlador va a llegar lleno con lo que traiga article %>
    </div>

    <div>
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<%end%>

app/views/articles/edit.html.erb
<div class="small-container center-block">
  <%= render "articles/form" %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">
  <h1>Mis articulos</h1>

  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">
  <%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div>
    <%= @article.content%>
</div>

<div>
    <%= link_to "Eliminar el artículo", @article, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Hola <%= current_user.email %></h1> 
<%# El current_user con su propiedad lo sacamos de schema %>
<%= link_to "Inicio", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice alert-primary"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-light padding">
  <li class="nav-item">
    <%= link_to "Inicio", root_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Articulos", articles_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Escribir", new_articles_path, class:"nav-link" %>
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"nav-link" %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to "Iniciar sesión", new_user_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Registro", new_user_registration_path, class:"nav-link" %>
    </li>
  <%end%>
</nav>